### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by guilhermemarconi** [Joezo/atom-jshint#100]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\exports\atom.js:48:11)
<unknown> (C:\Users\Marconi\.atom\packages\atom-jshint\lib\atom-jshint.js:15:26)
Object.<anonymous> (C:\Users\Marconi\.atom\packages\atom-jshint\lib\atom-jshint.js:307:3)
Module._compile (module.js:452:26)
Object..js (C:\Users\Marconi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\babel.js:162:21)
Module.load (module.js:347:32)
```

**Comment by Joezo** [comment]
All deprecations are fixed in branch fix-deprecations, this will be published soon. Thanks for reporting the issue :)
