### ISSUE TITLE
Invalid Result received from JSHint

### ISSUE THREAD

**Issue by mrextreme** [Joezo/atom-jshint#108]
This error message shows up every time I open a JS file:

```
Invalid Result received from JSHint
Check your console for more info
```

In the console it says:

```
events.js:141 Uncaught Error: write EPIPE
... /.atom/packages/linter-jshint/lib/main.coffee:41 JSHint Result: 
util.js:639 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.
events.js:141 Uncaught Error: write EPIPE
... /.atom/packages/linter-jshint/lib/main.coffee:41 JSHint Result: 
```

I have the latest Atom and JSHint installed on the latest, up-to-date OSX.

**Comment by renestalder** [comment]
I have the same issue. Latest Atom version.

**Comment by Exilz** [comment]
Same here. :(

**Comment by Joezo** [comment]
This one looks like it's coming from a different package. Sorry I can't help out with that one :( Can I suggest directing your issue over to linter-jshint where it looks like this is being thrown from :) https://github.com/AtomLinter/linter-jshint/issues
