### ISSUE TITLE
Object #<ReactEditorView> has no method 'lineElementForScreenRow'

### ISSUE THREAD

**Issue by blackat** [Joezo/atom-jshint#47]
Hi,
everytime I type I get this error
Uncaught TypeError: Object #<ReactEditorView> has no method 'lineElementForScreenRow' /Users/username/.atom/packages/jshint/index.js:22

I have the latest version of the plugin installed and atom 0.117.0.

Thanks a lot for your attention.
Eugenio

**Comment by Joezo** [comment]
I don't think Atom uses react anymore. (I might be wrong). Closing this and if its occurs again will reopen :)
