### ISSUE TITLE
Allow disable jshint for ".min.js" files

### ISSUE THREAD

**Issue by diazemiliano** [Joezo/atom-jshint#64]
It is not a bug but my atom editor, crashes when load a **".min.js"** file because a excessive computing. It will be nicer if we could filter files like **".min.js"**.

**Comment by impinball** [comment]
1. Syntax highlighters always struggle to properly highlight minified files. That's probably what's hogging all the resources, considering that may very well be causing literally hundreds if not thousands of UI updates with React. That's slow in *any* language, not just JavaScript. (Every other editor I've tried hangs when trying to highlight minified JS files, including Vim).
2. JSHint only catches so many "errors" with them, and AFAICT, this uses the default limit of 50 errors.

I don't think this package can really do anything about that.

Now, as for plain ol' JSHint, make sure this is in your .jshintignore:

```
**/*.min.js
```

**Comment by Joezo** [comment]
I think @impinball solution is great, just add it to your .jshintignore file :)
