### ISSUE TITLE
Typing "function" in a *.js file with atom-jshint enabled causes Atom to freeze

### ISSUE THREAD

**Issue by hail-seitan** [Joezo/atom-jshint#92]
I'm running Atom 0.187.0, on both Linux Mint 17.1 Rebecca x64 and Windows 7 x64. When I have Joezo/atom-jshint enabled, even if all my other non-standard packages are disabled, typing the word `function` at any point in a *.js file will cause Atom to instantly hang and I must force quit. No errors show up on the dev-tools js console or when I run `atom -f` in the console. It simply freezes.

Only "function" seems to cause this problem, I can type anything else without a problem. (!??)

If there is another way that Atom might be telling me what the error is, please let me know and I'll provide more info. (I haven't been able to find if atom logs errors to a file somewhere.) The bug is very replicable, on 2 different operating systems on 2 different computers.

This error also happens when I use the other jshint, sindresorhus/atom-jshint, with all other custom packages disabled.

What is going on??? Thanks.

**Comment by Joezo** [comment]
Sounds like something that was specific to a bad release of jshint itself, as it was affecting both atom packages. I'm going to close this in the hope that now we're on version 0.201.0 of atom and jshint has been updated, this problem will have solved itself. Please let me know if it hasn't though. (i published 2.0.0 of this package earlier today)
